### Get all users
GET http://localhost:3000/users

### Get user by id
GET http://localhost:3000/users/3

### Register user successfully
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "name": "Izan",
    "surname": "Gil",
    "username": "izangildev",
    "email": "izangildev@gmail.com",
    "birthDate": "2004-07-14",
    "password": "izangildev147"
}

### Register user with missing fields
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "surname": "Error",
    "username": "Sample",
    "email": "sampleError@gmail.com",
    "birthDate": "1947-01-01",
    "password": "needToEncrypt"
}

### login user successfully
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "username": "izangildev",
    "password": "izangildev147"
}

### login user with missing fields
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "username": "izangildev"
}

### Change password
PATCH http://localhost:3000/users/changePassword
Content-Type: application/json

{
    "username": "izangildev",
    "oldPassword": "MyNewPassword",
    "newPassword": "izangildev147"
}

### Change password with no fields
PATCH http://localhost:3000/users/changePassword
Content-Type: application/json

{
    "username": "izangildev",
    "oldPassword": "PASSWORD"
}

### Change username
PATCH http://localhost:3000/users/changeUsername
Content-Type: application/json

{
    "username": "johndoe",
    "password": "hashed_password1",
    "newUsername": "johndoe2"
}

### Change username with missing fields
PATCH http://localhost:3000/users/changeUsername
Content-Type: application/json

{
    "username": "johndoe",
    "newUsername": "johndoe2"
}

### Delete user
DELETE http://localhost:3000/users/delete
Content-Type: application/json

{
    "username": "bobjohnson",
    "password": "hashed_password4"
}

### Delete user with missing fields
DELETE http://localhost:3000/users/delete
Content-Type: application/json

{
    "username": "bobjohnson"
}